services:
#    _instanceof:
#        Contao\CoreBundle\Framework\FrameworkAwareInterface:
#            calls:
#                - ["setFramework", ["@contao.framework"]]

#        Symfony\Component\DependencyInjection\ContainerAwareInterface:
#            calls:
#                - ["setContainer", ["@service_container"]]

    _defaults:
        autoconfigure: true
        autowire: true
        public: true




    # backend controller
    IIDO\CoreBundle\Controller\Backend\WebsiteSettingsController:
        calls:
            - [setContainer, ['@service_container']]


    # frontend ajax controller
    IIDO\CoreBundle\Controller\Frontend\AjaxController:
        calls:
            - [ setContainer, [ '@service_container' ] ]


    # entity
#    IIDO\CoreBundle\Entity\ThemeDesignerEntity: ~

    # repository
    IIDO\CoreBundle\Repository\ThemeDesignerRepository:
        tags:
            - { name: doctrine.repository_service }


    # model
#    IIDO\CoreBundle\Model\ThemeDesignerModel: ~


    # twig
    IIDO\CoreBundle\Twig\TwigTemplatesExtension:
        public: false
        tags:
            - { name: twig.extension }


    # classes
    iido.core.website-settings.settings:
        class: IIDO\CoreBundle\Backend\WebsiteSettings

    iido.core.website-settings.themeDesigner:
        class: IIDO\CoreBundle\Backend\ThemeDesigner


    # event listener
    IIDO\CoreBundle\EventListener\BackendMenuListener:
        arguments:
            - "@router"
            - "@request_stack"

    IIDO\CoreBundle\EventListener\AjaxListener:
        arguments:
            - "@monolog.logger.contao"
            - "@contao.framework"

    IIDO\CoreBundle\EventListener\BackendTemplateListener: ~
    IIDO\CoreBundle\EventListener\FrontendTemplateListener: ~
    IIDO\CoreBundle\EventListener\InsertTagsListener: ~
    IIDO\CoreBundle\EventListener\PageListener: ~


    # dca tables listener
    IIDO\CoreBundle\EventListener\DataContainer\CoreSettingsListener: ~


    # event subscriber
    IIDO\CoreBundle\EventSubscriber\KernelRequestSubscriber:
        arguments:
            - "@contao.routing.scope_matcher"


    # service
    iido.core.service.file_uploader:
        class: IIDO\CoreBundle\Services\FileUploader
